### GET /posts
GET http://localhost:3000/posts HTTP/1.1

### GET /posts/1
GET http://localhost:3000/posts/5f0983ec7b7e6d5b648e41c6 HTTP/1.1

### with invalid id
GET http://localhost:3000/posts/9 HTTP/1.1

### POST /posts
POST http://localhost:3000/posts HTTP/1.1
content-type: application/json

{
    "title": "All Good Job",
    "username": "amrits",
	"category": "code",
	"content": "this is a new post about code"
}

### POST /posts (with no category)
POST http://localhost:3000/posts HTTP/1.1
content-type: application/json

{
    "title": "GOOOOOOOOOOOOdJOB",
    "username": "tester",
	"content": "this is a new post about code"
}

### DELETE /posts/id 

DELETE http://localhost:3000/posts/5f098f2529b8d15f1aa55333 HTTP/1.1

### PUT /posts/1
PUT http://localhost:3000/posts/5f09888dd6a1365e272b930a HTTP/1.1
content-type: application/json

{
    "title": "updated post",
    "username": "amritk",
	"category": "general",
	"content": "this post has been updated"
}

### PUT /posts/1 (no category)
PUT http://localhost:3000/posts/5f0861372388a52d7b02b935 HTTP/1.1
content-type: application/json

{
    "title": "updated post",
    "username": "amritk",
	"content": "this post has been updated"
}

### POST /auth/login 
POST http://localhost:3000/auth/login
content-type: application/json

{
	"username": "amrits",
	"password": "abc123"
}
### GET /auth/logout
GET http://localhost:3000/auth/logout

### POST /auth/register 
POST http://localhost:3000/auth/register
content-type: application/json

{
	"username": "amrits",
	"email": "auto-tester1@abc.com",
	"password": "abc123"
}